# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=1.3.0
maven_group=de.larsensmods.jeiworldgen
archives_name=JEIWorldGen

version=1.3.0
group=de.larsensmods.jeiworldgen
java_version=25

# Minecraft properties
minecraft_version=26.2
mod_name=JEIWorldGen
mod_author=LarsenR
mod_id=jeiworldgen
license=GPL3.0-only
credits=
description=JEI/REI Addon for ore and world generation
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# FabricMC
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.3-beta
neoforge_loader_version_range=[4,)

# Dependencies
jei_version=30.0.0.1
rei_version=26.2.820
architectury_version=21.0.2