modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "jeiworldgen"
version = "${version}"
displayName = "JEIWorldGen"
authors = "LarsenR"
description = '''
WorldGen Info Pages for JustEnoughItems (JEI)
'''
logoFile = "icon.png"
displayTest = "NONE"

[[dependencies.jeiworldgen]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jeiworldgen]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jeiworldgen]]
modId = "jei"
type = "optional"
versionRange = "[19.25.1.326,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "jeiworldgen.mixins.json"
